# Generated by Django 3.1.12 on 2023-01-24 22:13

import SmartDjango.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', SmartDjango.models.fields.DateField(verbose_name='日期')),
                ('start', SmartDjango.models.fields.DateTimeField(verbose_name='开始时间')),
                ('end', SmartDjango.models.fields.DateTimeField(verbose_name='结束时间')),
                ('start_upload', SmartDjango.models.fields.PositiveIntegerField(default=0, verbose_name='开始上传数据量')),
                ('start_download', SmartDjango.models.fields.PositiveIntegerField(default=0, verbose_name='开始下载数据量')),
                ('end_upload', SmartDjango.models.fields.PositiveIntegerField(default=0, verbose_name='结束上传数据量')),
                ('end_download', SmartDjango.models.fields.PositiveIntegerField(default=0, verbose_name='结束下载数据量')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', SmartDjango.models.fields.DateField(verbose_name='日期')),
                ('rate', SmartDjango.models.fields.CharField(max_length=10, verbose_name='速率')),
                ('upload', SmartDjango.models.fields.PositiveIntegerField(default=0, verbose_name='上传数据量')),
                ('download', SmartDjango.models.fields.PositiveIntegerField(default=0, verbose_name='下载数据量')),
            ],
            options={
                'unique_together': {('date', 'rate')},
            },
        ),
    ]
