# Generated by Django 3.0.6 on 2021-10-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.fields.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_id', models.fields.CharField(max_length=6, unique=True)),
                ('create_time', models.fields.DateTimeField(auto_now_add=True)),
                ('key', models.fields.CharField(max_length=100, unique=True)),
                ('width', models.fields.IntegerField()),
                ('height', models.fields.IntegerField()),
                ('color_average', models.fields.CharField(default=None, max_length=20, null=True)),
                ('mime_type', models.fields.CharField(max_length=50)),
                ('orientation', models.fields.IntegerField(default=1)),
                ('pinned', models.BooleanField(default=False)),
                ('album', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Foto.Album')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
